#!/bin/bash

# The directory of the scripts
DIR={{SCRIPT_PATH}}

# the script name
CMD=$1
shift

# Run the command
# Check if the command includes the .sh extension
if [[ $CMD == *.sh ]]
then
    # If it does, run the command without adding .sh
    bash "${DIR}/${CMD}" "$@"
else
    # If it doesn't, add .sh before running the command
    bash "${DIR}/${CMD}.sh" "$@"
fi